// Port lekkiej lokalizacji z Localization.cs (aplikacja WPF).
// Stała kolejność języków: [en, pl, es, de, fr, ja, zh]. Brakujący wpis → angielski.
// W Etapie 0 portujemy podzbiór kluczy; kolejne dochodzą wraz z funkcjami.

export const LANGUAGES: { code: string; nativeName: string }[] = [
  { code: "en", nativeName: "English" },
  { code: "pl", nativeName: "Polski" },
  { code: "es", nativeName: "Español" },
  { code: "de", nativeName: "Deutsch" },
  { code: "fr", nativeName: "Français" },
  { code: "ja", nativeName: "日本語" },
  { code: "zh", nativeName: "中文" },
];

// [en, pl, es, de, fr, ja, zh]
const MAP: Record<string, string[]> = {
  "View.Structure": ["Structure", "Struktura", "Estructura", "Struktur", "Structure", "構造", "结构"],
  "View.Properties": ["Properties", "Właściwości", "Propiedades", "Eigenschaften", "Propriétés", "プロパティ", "属性"],
  "Pane.Close": ["Close panel", "Zamknij panel", "Cerrar panel", "Bereich schließen", "Fermer le panneau", "パネルを閉じる", "关闭面板"],
  "Pane.OpenStructure": ["Show Structure", "Pokaż Strukturę", "Mostrar Estructura", "Struktur anzeigen", "Afficher la structure", "構造を表示", "显示结构"],
  "Pane.OpenProperties": ["Show Properties", "Pokaż Właściwości", "Mostrar Propiedades", "Eigenschaften anzeigen", "Afficher les propriétés", "プロパティを表示", "显示属性"],
  "View.Preview": ["Preview", "Podgląd", "Vista previa", "Vorschau", "Aperçu", "プレビュー", "预览"],
  "View.Source": ["Source", "Źródło", "Código", "Quelltext", "Source", "ソース", "源代码"],
  "View.Design": ["Design", "Projekt", "Diseño", "Entwurf", "Conception", "デザイン", "设计"],
  "View.Changes": ["Changes", "Zmiany", "Cambios", "Änderungen", "Modifications", "変更", "更改"],
  "Changes.Title": ["Changes", "Zmiany", "Cambios", "Änderungen", "Modifications", "変更", "更改"],
  "Changes.Empty": ["No changes since last save", "Brak zmian od ostatniego zapisu", "Sin cambios desde el último guardado", "Keine Änderungen seit dem letzten Speichern", "Aucune modification depuis le dernier enregistrement", "前回の保存以降の変更はありません", "自上次保存以来没有更改"],
  "Changes.RevertAll": ["Revert all", "Cofnij wszystko", "Revertir todo", "Alle zurücksetzen", "Tout annuler", "すべて元に戻す", "全部还原"],
  "Changes.InlineDiff": ["Show changes in code", "Pokaż zmiany w kodzie", "Mostrar cambios en el código", "Änderungen im Code anzeigen", "Afficher les modifications dans le code", "コードに変更を表示", "在代码中显示更改"],
  "Changes.Revert": ["Revert", "Przywróć", "Revertir", "Zurücksetzen", "Annuler", "元に戻す", "还原"],
  "Changes.Line": ["Line {0}", "Linia {0}", "Línea {0}", "Zeile {0}", "Ligne {0}", "行 {0}", "第 {0} 行"],
  "Changes.Added": ["Added (line {0})", "Dodano (linia {0})", "Añadido (línea {0})", "Hinzugefügt (Zeile {0})", "Ajouté (ligne {0})", "追加 (行 {0})", "已添加（第 {0} 行）"],
  "Changes.Removed": ["Removed (line {0})", "Usunięto (linia {0})", "Eliminado (línea {0})", "Entfernt (Zeile {0})", "Supprimé (ligne {0})", "削除 (行 {0})", "已删除（第 {0} 行）"],
  "Changes.Moved": ["Moved (line {0} → {1})", "Przeniesiono (linia {0} → {1})", "Movido (línea {0} → {1})", "Verschoben (Zeile {0} → {1})", "Déplacé (ligne {0} → {1})", "移動 (行 {0} → {1})", "已移动（第 {0} → {1} 行）"],
  "Settings.Title": ["Settings", "Ustawienia", "Configuración", "Einstellungen", "Paramètres", "設定", "设置"],
  "Settings.Language": ["Language", "Język", "Idioma", "Sprache", "Langue", "言語", "语言"],
  "Language.FollowVsCode": ["Use VS Code language", "Język VS Code", "Usar el idioma de VS Code", "VS-Code-Sprache verwenden", "Utiliser la langue de VS Code", "VS Code の言語を使用", "使用 VS Code 语言"],
  "Settings.LanguageNote": ["After changing, reload the editor (Ctrl+R) to apply.", "Po zmianie przeładuj edytor (Ctrl+R), aby zastosować.", "Tras cambiar, recarga el editor (Ctrl+R) para aplicar.", "Nach der Änderung den Editor neu laden (Strg+R), um sie anzuwenden.", "Après modification, rechargez l'éditeur (Ctrl+R) pour appliquer.", "変更後、エディターを再読み込み（Ctrl+R）して適用してください。", "更改后请重新加载编辑器（Ctrl+R）以生效。"],
  "Settings.OpenExtSettings": ["Open extension settings…", "Otwórz ustawienia rozszerzenia…", "Abrir la configuración de la extensión…", "Erweiterungseinstellungen öffnen…", "Ouvrir les paramètres de l'extension…", "拡張機能の設定を開く…", "打开扩展设置…"],
  "Settings.Advanced": ["Advanced — WPF host", "Zaawansowane — host WPF", "Avanzado — host WPF", "Erweitert — WPF-Host", "Avancé — hôte WPF", "詳細設定 — WPF ホスト", "高级 — WPF 宿主"],
  "Settings.Sync": ["Selection sync", "Synchronizacja zaznaczenia", "Sincronización de selección", "Auswahl-Synchronisierung", "Synchronisation de la sélection", "選択の同期", "选择同步"],
  "Sync.ToText": ["Select in the text editor", "Zaznaczaj w edytorze tekstu", "Seleccionar en el editor de texto", "Im Texteditor auswählen", "Sélectionner dans l'éditeur de texte", "テキストエディターで選択", "在文本编辑器中选择"],
  "Sync.FromText": ["Select in XVE from the text cursor", "Zaznaczaj w XVE wg kursora w tekście", "Seleccionar en XVE según el cursor de texto", "In XVE per Textcursor auswählen", "Sélectionner dans XVE selon le curseur", "テキストカーソルで XVE を選択", "根据文本光标在 XVE 中选择"],
  "Sync.Note": ["Two-way selection sync with a side-by-side text editor.", "Dwukierunkowa synchronizacja zaznaczenia z edytorem tekstu obok.", "Sincronización bidireccional con el editor de texto adyacente.", "Bidirektionale Synchronisierung mit dem danebenliegenden Texteditor.", "Synchronisation bidirectionnelle avec l'éditeur de texte adjacent.", "隣のテキストエディターと双方向で選択を同期します。", "与并排文本编辑器的双向选择同步。"],
  "Settings.Backend": ["Preview backend", "Silnik podglądu", "Motor de vista previa", "Vorschau-Engine", "Moteur d'aperçu", "プレビューエンジン", "预览引擎"],
  "Backend.Auto": ["Auto", "Automatyczny", "Automático", "Automatisch", "Automatique", "自動", "自动"],
  "Backend.Web": ["Web (cross-platform)", "Web (wieloplatformowy)", "Web (multiplataforma)", "Web (plattformübergreifend)", "Web (multiplateforme)", "Web（クロスプラットフォーム）", "Web（跨平台）"],
  "Backend.WpfHost": ["WPF host (Windows, high fidelity)", "Host WPF (Windows, wysoka wierność)", "Host WPF (Windows, alta fidelidad)", "WPF-Host (Windows, hohe Treue)", "Hôte WPF (Windows, haute fidélité)", "WPF ホスト（Windows、高忠実度）", "WPF 宿主（Windows，高保真）"],
  "Backend.WindowsOnly": ["WPF host is available only on Windows.", "Host WPF jest dostępny tylko na Windows.", "El host WPF solo está disponible en Windows.", "WPF-Host ist nur unter Windows verfügbar.", "L'hôte WPF n'est disponible que sous Windows.", "WPF ホストは Windows でのみ利用できます。", "WPF 宿主仅在 Windows 上可用。"],
  "Backend.WpfHostIsolated": ["WPF host — isolated (separate resources)", "Host WPF — izolowany (osobne zasoby)", "Host WPF — aislado (recursos separados)", "WPF-Host — isoliert (eigene Ressourcen)", "Hôte WPF — isolé (ressources distinctes)", "WPF ホスト — 分離（個別リソース）", "WPF 宿主 — 隔离（独立资源）"],
  "Isolation.Note": ["Isolated runs a separate WPF host with its own resources for this file — use it for files outside the open project so other windows' resources don't change how it looks.", "Izolowany uruchamia osobny host WPF z własnymi zasobami dla tego pliku — użyj dla plików spoza otwartego projektu, by zasoby innych okien nie zmieniały jego wyglądu.", "Aislado ejecuta un host WPF independiente con sus propios recursos para este archivo — úsalo para archivos fuera del proyecto abierto.", "Isoliert startet einen separaten WPF-Host mit eigenen Ressourcen für diese Datei — für Dateien außerhalb des geöffneten Projekts.", "Isolé exécute un hôte WPF distinct avec ses propres ressources pour ce fichier — pour les fichiers hors du projet ouvert.", "分離は、このファイル専用のリソースを持つ別の WPF ホストを実行します。開いているプロジェクト外のファイルに使用します。", "隔离为此文件运行带有独立资源的单独 WPF 宿主，适用于打开项目之外的文件。"],
  "Isolation.ProposeMsg": ["The file “{0}” is outside the open project/workspace. Open its preview in an isolated WPF host (separate resources) so resources loaded by other windows don't change how it looks?", "Plik „{0}” jest spoza otwartego projektu/obszaru roboczego. Otworzyć jego podgląd w izolowanym hoście WPF (osobne zasoby), aby zasoby załadowane w innych oknach nie wpływały na jego wygląd?", "El archivo «{0}» está fuera del proyecto/espacio de trabajo abierto. ¿Abrir su vista previa en un host WPF aislado (recursos separados) para que los recursos de otras ventanas no cambien su apariencia?", "Die Datei „{0}“ liegt außerhalb des geöffneten Projekts/Arbeitsbereichs. Vorschau in einem isolierten WPF-Host (eigene Ressourcen) öffnen, damit Ressourcen anderer Fenster ihr Aussehen nicht verändern?", "Le fichier « {0} » est en dehors du projet/espace de travail ouvert. Ouvrir son aperçu dans un hôte WPF isolé (ressources distinctes) pour que les ressources des autres fenêtres ne modifient pas son apparence ?", "ファイル「{0}」は開いているプロジェクト/ワークスペースの外にあります。他のウィンドウで読み込まれたリソースが表示に影響しないよう、分離された WPF ホスト（個別リソース）でプレビューを開きますか？", "文件“{0}”在已打开的项目/工作区之外。是否在隔离的 WPF 宿主（独立资源）中打开其预览，以免其他窗口加载的资源改变其外观？"],
  "Isolation.ProposeIsolate": ["Isolated host", "Izolowany host", "Host aislado", "Isolierter Host", "Hôte isolé", "分離ホスト", "隔离宿主"],
  "Isolation.ProposeAuto": ["Auto-isolate, don't ask again", "Automatycznie izoluj, nie pytaj więcej", "Aislar automáticamente, no preguntar más", "Automatisch isolieren, nicht mehr fragen", "Isoler automatiquement, ne plus demander", "自動的に分離し、今後確認しない", "需要时自动隔离，不再询问"],
  "Isolation.ProposeShare": ["Shared host", "Wspólny host", "Host compartido", "Gemeinsamer Host", "Hôte partagé", "共有ホスト", "共享宿主"],
  "Settings.Isolation": ["WPF host isolation", "Izolacja hosta WPF", "Aislamiento del host WPF", "WPF-Host-Isolierung", "Isolation de l'hôte WPF", "WPF ホストの分離", "WPF 宿主隔离"],
  "Isolation.Ask": ["Ask whether to isolate", "Pytaj, czy izolować", "Preguntar si aislar", "Fragen, ob isoliert werden soll", "Demander s'il faut isoler", "分離するか確認する", "询问是否隔离"],
  "Isolation.Auto": ["Auto-isolate when needed", "Automatycznie izoluj, gdy trzeba", "Aislar automáticamente cuando sea necesario", "Bei Bedarf automatisch isolieren", "Isoler automatiquement si nécessaire", "必要なときに自動で分離", "需要时自动隔离"],
  "Isolation.Always": ["Always isolate", "Zawsze izoluj", "Aislar siempre", "Immer isolieren", "Toujours isoler", "常に分離する", "始终隔离"],
  "Isolation.Never": ["Never isolate (shared host)", "Nigdy nie izoluj (wspólny host)", "Nunca aislar (host compartido)", "Nie isolieren (gemeinsamer Host)", "Ne jamais isoler (hôte partagé)", "分離しない（共有ホスト）", "从不隔离（共享宿主）"],
  "Isolation.SettingNote": ["Isolating runs a separate WPF host with its own resources for files from another project or with no project.", "Izolacja uruchamia osobny host WPF z własnymi zasobami dla plików spoza projektu lub bez projektu.", "El aislamiento ejecuta un host WPF independiente con sus propios recursos para archivos de otro proyecto o sin proyecto.", "Die Isolierung startet einen separaten WPF-Host mit eigenen Ressourcen für Dateien aus einem anderen Projekt oder ohne Projekt.", "L'isolation exécute un hôte WPF distinct avec ses propres ressources pour les fichiers d'un autre projet ou sans projet.", "分離は、別プロジェクトまたはプロジェクト外のファイル用に専用リソースを持つ別の WPF ホストを実行します。", "隔离会为来自其他项目或无项目的文件运行带有独立资源的单独 WPF 宿主。"],
  "Settings.PreviewTheme": ["Preview theme (WPF host)", "Motyw podglądu (host WPF)", "Tema de vista previa (host WPF)", "Vorschau-Thema (WPF-Host)", "Thème d'aperçu (hôte WPF)", "プレビューテーマ（WPF ホスト）", "预览主题（WPF 宿主）"],
  "Theme.Classic": ["Classic", "Klasyczny", "Clásico", "Klassisch", "Classique", "クラシック", "经典"],
  "Theme.Classic98": ["Classic '98", "Klasyczny '98", "Clásico '98", "Klassisch '98", "Classique '98", "クラシック '98", "经典 '98"],
  "Theme.System": ["System (Fluent)", "Systemowy (Fluent)", "Sistema (Fluent)", "System (Fluent)", "Système (Fluent)", "システム（Fluent）", "系统（Fluent）"],
  "Theme.Light": ["Light (Fluent)", "Jasny (Fluent)", "Claro (Fluent)", "Hell (Fluent)", "Clair (Fluent)", "ライト（Fluent）", "浅色（Fluent）"],
  "Theme.Dark": ["Dark (Fluent)", "Ciemny (Fluent)", "Oscuro (Fluent)", "Dunkel (Fluent)", "Sombre (Fluent)", "ダーク（Fluent）", "深色（Fluent）"],
  "Theme.Native": ["Native web (Linux)", "Natywny web (Linux)", "Web nativo (Linux)", "Natives Web (Linux)", "Web natif (Linux)", "ネイティブ Web（Linux）", "原生 Web（Linux）"],
  "Theme.ProjectSep": ["— project themes —", "— motywy projektu —", "— temas del proyecto —", "— Projekt-Themes —", "— thèmes du projet —", "— プロジェクトのテーマ —", "— 项目主题 —"],
  "Theme.StdSep": ["— standard —", "— standardowe —", "— estándar —", "— Standard —", "— standard —", "— 標準 —", "— 标准 —"],
  "Settings.RenderScale": ["Render scale (WPF host)", "Skala renderu (host WPF)", "Escala de render (host WPF)", "Render-Skalierung (WPF-Host)", "Échelle de rendu (hôte WPF)", "レンダリング倍率（WPF ホスト）", "渲染倍率（WPF 宿主）"],
  "RenderScale.Auto": ["Screen resolution (auto)", "Rozdzielczość ekranu (auto)", "Resolución de pantalla (auto)", "Bildschirmauflösung (auto)", "Résolution d'écran (auto)", "画面解像度（自動）", "屏幕分辨率（自动）"],
  "Settings.DragPreview": ["Drag preview", "Podgląd przeciągania", "Vista previa al arrastrar", "Ziehen-Vorschau", "Aperçu du glissement", "ドラッグプレビュー", "拖动预览"],
  "Drag.Overlay": ["Overlay only (pixels snap on release)", "Tylko nakładka (piksele skaczą na końcu)", "Solo superposición (los píxeles saltan al soltar)", "Nur Overlay (Pixel springen beim Loslassen)", "Superposition seule (pixels au relâchement)", "オーバーレイのみ（離すとピクセルが移動）", "仅叠加层（释放时像素跳到位）"],
  "Drag.Frames": ["Live re-render every", "Re-render na żywo co", "Recomponer en vivo cada", "Live neu rendern alle", "Re-rendu en direct toutes les", "ライブ再描画", "实时重绘每"],
  "Drag.Ms": ["Live re-render every", "Re-render na żywo co", "Recomponer en vivo cada", "Live neu rendern alle", "Re-rendu en direct toutes les", "ライブ再描画", "实时重绘每"],
  "Drag.UnitFrames": ["frames", "klatek", "fotogramas", "Frames", "images", "フレーム", "帧"],
  "Drag.Session": ["Persistent host session (faster)", "Trwała sesja hosta (szybciej)", "Sesión persistente del host (más rápido)", "Persistente Host-Sitzung (schneller)", "Session d'hôte persistante (plus rapide)", "永続ホストセッション（高速）", "持久宿主会话（更快）"],
  "Drag.Coalesce": ["Drop stale frames (one in flight)", "Odrzucaj zaległe klatki (jedna w locie)", "Descartar fotogramas obsoletos (uno en curso)", "Veraltete Frames verwerfen (einer in Bearbeitung)", "Ignorer les images obsolètes (une en cours)", "古いフレームを破棄（同時1枚）", "丢弃过期帧（同时一帧）"],
  "Drag.OnChange": ["Render only on change", "Renderuj tylko przy zmianie", "Renderizar solo al cambiar", "Nur bei Änderung rendern", "Rendre uniquement au changement", "変更時のみレンダリング", "仅在变化时渲染"],
  "Drag.AdaptiveRes": ["Adaptive resolution (low while moving)", "Adaptacyjna rozdzielczość (niska w ruchu)", "Resolución adaptativa (baja en movimiento)", "Adaptive Auflösung (niedrig in Bewegung)", "Résolution adaptative (basse en mouvement)", "適応解像度（移動中は低）", "自适应分辨率（移动时降低）"],
  "Drag.MotionRes": ["Motion render resolution: ", "Rozdzielczość renderu w ruchu: ", "Resolución de render en movimiento: ", "Render-Auflösung in Bewegung: ", "Résolution de rendu en mouvement : ", "移動中のレンダリング解像度: ", "移动时渲染分辨率："],
  "Drag.AdaptiveFps": ["Use below: ", "Użyj poniżej: ", "Usar por debajo de: ", "Verwenden unter: ", "Utiliser en dessous de : ", "これ未満で使用: ", "低于此值时使用："],
  "Drag.AdaptiveFpsAlways": ["0 = always", "0 = zawsze", "0 = siempre", "0 = immer", "0 = toujours", "0 = 常に", "0 = 始终"],
  "Drag.MaxRes": ["Max render resolution (0 = unlimited): ", "Maks. rozdzielczość renderu (0 = bez limitu): ", "Resolución máx. (0 = sin límite): ", "Max. Renderauflösung (0 = unbegrenzt): ", "Résolution max. (0 = illimitée) : ", "最大解像度（0=無制限）: ", "最大渲染分辨率（0=无限制）："],
  "Drag.Viewport": ["Render only visible area (sharp, experimental)", "Renderuj tylko widoczny obszar (ostro, eksperymentalne)", "Renderizar solo el área visible (nítido, experimental)", "Nur sichtbaren Bereich rendern (scharf, experimentell)", "Rendre uniquement la zone visible (net, expérimental)", "表示領域のみレンダリング（鮮明・実験的）", "仅渲染可见区域（清晰，实验性）"],
  "Settings.CapBasis": ["Resolution cap basis", "Podstawa limitu rozdzielczości", "Base del límite de resolución", "Basis der Auflösungsgrenze", "Base de la limite de résolution", "解像度上限の基準", "分辨率上限基准"],
  "CapBasis.Visible": ["Visible area only", "Tylko widoczny obszar", "Solo área visible", "Nur sichtbarer Bereich", "Zone visible uniquement", "表示領域のみ", "仅可见区域"],
  "CapBasis.Slice": ["Whole slice (with overscan)", "Cały wycinek (z overscanem)", "Toda la porción (con overscan)", "Ganzer Ausschnitt (mit Overscan)", "Tranche entière (avec overscan)", "スライス全体（オーバースキャン含む）", "整个切片（含过扫描）"],
  "Settings.Overscan": ["Overscan: ", "Overscan: ", "Overscan: ", "Overscan: ", "Surbalayage : ", "オーバースキャン: ", "过扫描："],
  "Settings.DebugConsole": ["Debug in Console", "Debuguj w konsoli", "Depurar en consola", "Im Konsolen-Debug", "Déboguer dans la console", "コンソールでデバッグ", "在控制台调试"],
  "Settings.ConsoleOnStart": ["Show console while host starts", "Pokaż konsolę przy starcie hosta", "Mostrar consola al iniciar el host", "Konsole beim Host-Start anzeigen", "Afficher la console au démarrage de l'hôte", "ホスト起動時にコンソールを表示", "宿主启动时显示控制台"],
  "Debug.Title": ["Debug — WPF host", "Debug — host WPF", "Depuración — host WPF", "Debug — WPF-Host", "Débogage — hôte WPF", "デバッグ — WPF ホスト", "调试 — WPF 宿主"],
  "Debug.LiveDrag": ["Live when drag", "Na żywo przy przeciąganiu", "En vivo al arrastrar", "Live beim Ziehen", "En direct au glissement", "ドラッグ中もライブ", "拖动时实时"],
  "Debug.ResetAvg": ["Reset average render time", "Resetuj średni czas renderu", "Restablecer tiempo medio de render", "Durchschnittliche Renderzeit zurücksetzen", "Réinitialiser le temps de rendu moyen", "平均レンダリング時間をリセット", "重置平均渲染时间"],
  "Drag.Note": ["Applies to WPF host (PNG) mode. Web mode is always live.", "Dotyczy trybu WPF host (PNG). Tryb web jest zawsze na żywo.", "Se aplica al modo WPF host (PNG). El modo web siempre es en vivo.", "Gilt für WPF-Host (PNG). Web-Modus ist immer live.", "S'applique au mode hôte WPF (PNG). Le mode web est toujours en direct.", "WPF ホスト（PNG）モードに適用。Web モードは常にライブ。", "适用于 WPF 宿主（PNG）模式。Web 模式始终为实时。"],
  "View.NoSelection": ["No element selected", "Nie wybrano elementu", "Ningún elemento seleccionado", "Kein Element ausgewählt", "Aucun élément sélectionné", "要素が選択されていません", "未选择元素"],
  "Prop.Add": ["Add property…", "Dodaj właściwość…", "Agregar propiedad…", "Eigenschaft hinzufügen…", "Ajouter une propriété…", "プロパティを追加…", "添加属性…"],
  "Prop.Remove": ["Remove property", "Usuń właściwość", "Quitar propiedad", "Eigenschaft entfernen", "Supprimer la propriété", "プロパティを削除", "删除属性"],
  "Prop.Revert": ["Revert to saved value", "Przywróć zapisaną wartość", "Revertir al valor guardado", "Auf gespeicherten Wert zurücksetzen", "Rétablir la valeur enregistrée", "保存値に戻す", "还原为已保存的值"],
  "Prop.BrowseImage": ["Choose image…", "Wybierz obraz…", "Elegir imagen…", "Bild auswählen…", "Choisir une image…", "画像を選択…", "选择图片…"],
  "Add.Group.Containers": ["Containers", "Kontenery", "Contenedores", "Container", "Conteneurs", "コンテナー", "容器"],
  "Add.Group.Controls": ["Controls", "Kontrolki", "Controles", "Steuerelemente", "Contrôles", "コントロール", "控件"],
  "Add.Group.Lists": ["Lists", "Listy", "Listas", "Listen", "Listes", "リスト", "列表"],
  "Add.Group.Shapes": ["Shapes", "Kształty", "Formas", "Formen", "Formes", "シェイプ", "形状"],
  "Prop.Alpha": ["Opacity (alpha 0–255)", "Przezroczystość (alfa 0–255)", "Opacidad (alfa 0–255)", "Deckkraft (Alpha 0–255)", "Opacité (alpha 0–255)", "不透明度（アルファ 0–255）", "不透明度（Alpha 0–255）"],
  "Tb.Add": ["Add", "Dodaj", "Agregar", "Hinzufügen", "Ajouter", "追加", "添加"],
  "Tb.AddTip": ["Add element into the selected container", "Dodaj element do zaznaczonego kontenera", "Agregar elemento al contenedor seleccionado", "Element zum ausgewählten Container hinzufügen", "Ajouter un élément au conteneur sélectionné", "選択したコンテナーに要素を追加", "将元素添加到所选容器"],
  "Tb.Delete": ["Delete", "Usuń", "Eliminar", "Löschen", "Supprimer", "削除", "删除"],
  "Tb.DeleteTip": ["Delete the selected element (Del)", "Usuń zaznaczony element (Del)", "Eliminar el elemento seleccionado (Supr)", "Ausgewähltes Element löschen (Entf)", "Supprimer l'élément sélectionné (Suppr)", "選択した要素を削除 (Del)", "删除所选元素 (Del)"],
  "Tb.RunWindow": ["Run window", "Uruchom okno", "Iniciar ventana", "Fenster ausführen", "Lancer la fenêtre", "ウィンドウを実行", "运行窗口"],
  "Tb.RunWindowTip": ["Open XAML in a real Windows window", "Otwórz XAML w prawdziwym oknie Windows", "Abrir XAML en una ventana real de Windows", "XAML in einem echten Windows-Fenster öffnen", "Ouvrir le XAML dans une vraie fenêtre Windows", "実際の Windows ウィンドウで XAML を开く", "在真实 Windows 窗口中打开 XAML"],
  "Run.Snapshot": ["Snapshot (one-time)", "Migawka (jednorazowo)", "Instantánea (una vez)", "Schnappschuss (einmalig)", "Instantané (une fois)", "スナップショット（1回）", "快照（一次性）"],
  "Run.Live": ["Live (updates with the project)", "Na żywo (aktualizuje się z projektem)", "En vivo (se actualiza con el proyecto)", "Live (aktualisiert mit dem Projekt)", "En direct (mis à jour avec le projet)", "ライブ（プロジェクトと共に更新）", "实时（随项目更新）"],
  "Run.LiveBadge": ["on live", "na żywo", "en vivo", "live", "en direct", "ライブ", "实时"],
  "Tb.ResourcesTip": ["Load project resources (DLLs / styles / dictionaries) into the preview", "Wczytaj zasoby projektu (DLL / style / słowniki) do podglądu", "Cargar recursos del proyecto (DLL / estilos / diccionarios) en la vista previa", "Projektressourcen (DLLs / Stile / Wörterbücher) in die Vorschau laden", "Charger les ressources du projet (DLL / styles / dictionnaires) dans l'aperçu", "プロジェクトのリソース（DLL / スタイル / 辞書）をプレビューに読み込む", "将项目资源（DLL / 样式 / 字典）加载到预览"],
  "Tb.Undo": ["Undo", "Cofnij", "Deshacer", "Rückgängig", "Annuler", "元に戻す", "撤销"],
  "Tb.Redo": ["Redo", "Ponów", "Rehacer", "Wiederholen", "Rétablir", "やり直し", "重做"],
  "Toolbar.Move": ["Drag to move the toolbar (drop near an edge to dock)", "Przeciągnij, aby przenieść pasek (upuść przy krawędzi, by zadokować)", "Arrastra para mover la barra (suelta cerca de un borde para anclar)", "Ziehen zum Verschieben der Leiste (an einer Kante andocken)", "Glissez pour déplacer la barre (déposez près d'un bord pour ancrer)", "ドラッグでツールバーを移動（端でドッキング）", "拖动以移动工具栏（靠近边缘可停靠）"],
  "Toolbar.Pin": ["Pin as a fixed bar beside the preview", "Przypnij jako stały pasek obok podglądu", "Fijar como barra fija junto a la vista previa", "Als feste Leiste neben der Vorschau anheften", "Épingler comme barre fixe à côté de l'aperçu", "プレビュー横の固定バーとして固定", "固定为预览旁的固定栏"],
  "Toolbar.Unpin": ["Unpin to a floating bar over the preview", "Odepnij do pływającego paska nad podglądem", "Desfijar a una barra flotante sobre la vista previa", "Als schwebende Leiste über der Vorschau lösen", "Détacher en barre flottante sur l'aperçu", "プレビュー上の浮動バーに戻す", "取消固定为预览上的浮动栏"],
  "Toolbar.Resize": ["Drag to resize the toolbar", "Przeciągnij, aby zmienić rozmiar paska", "Arrastra para redimensionar la barra", "Ziehen, um die Leiste zu skalieren", "Glissez pour redimensionner la barre", "ドラッグでツールバーのサイズを変更", "拖动以调整工具栏大小"],
  "Host.Inactive": ["WPF host inactive (web engine)", "Host WPF nieaktywny (silnik web)", "Host WPF inactivo (motor web)", "WPF-Host inaktiv (Web-Engine)", "Hôte WPF inactif (moteur web)", "WPF ホスト非アクティブ（Web エンジン）", "WPF 主机未激活（Web 引擎）"],
  "Host.Ok": ["WPF host: OK", "Host WPF: OK", "Host WPF: OK", "WPF-Host: OK", "Hôte WPF : OK", "WPF ホスト: OK", "WPF 主机：正常"],
  "Host.Error": ["WPF host: error", "Host WPF: błąd", "Host WPF: error", "WPF-Host: Fehler", "Hôte WPF : erreur", "WPF ホスト: エラー", "WPF 主机：错误"],
  "Host.Idle": ["WPF host: starting…", "Host WPF: uruchamianie…", "Host WPF: iniciando…", "WPF-Host: startet…", "Hôte WPF : démarrage…", "WPF ホスト: 起動中…", "WPF 主机：启动中…"],
  "Host.Isolated": ["isolated", "izolowany", "aislado", "isoliert", "isolé", "分離", "隔离"],
  "Host.ClickLog": ["click for log", "kliknij, aby zobaczyć log", "clic para ver el registro", "für Protokoll klicken", "cliquer pour le journal", "クリックでログ表示", "点击查看日志"],
  "Host.LogTitle": ["Console — Log", "Konsola — Log", "Consola — Registro", "Konsole — Protokoll", "Console — Journal", "コンソール — ログ", "控制台 — 日志"],
  // Twarde awarie hosta WPF (powiadomienia w oknie VS Code, nie w webview)
  "Host.RuntimeMissing": ["The WPF preview host needs the .NET 10 Desktop Runtime, which is not installed. Falling back to the web renderer.", "Host podglądu WPF wymaga środowiska .NET 10 Desktop Runtime, którego nie zainstalowano. Przełączam na renderer web.", "El host de vista previa WPF necesita .NET 10 Desktop Runtime, que no está instalado. Se usará el renderizador web.", "Der WPF-Vorschau-Host benötigt die .NET 10 Desktop Runtime, die nicht installiert ist. Es wird auf den Web-Renderer zurückgegriffen.", "L'hôte d'aperçu WPF nécessite le .NET 10 Desktop Runtime, qui n'est pas installé. Retour au moteur de rendu web.", "WPF プレビューホストには .NET 10 Desktop Runtime が必要ですが、インストールされていません。Web レンダラーに切り替えます。", "WPF 预览主机需要未安装的 .NET 10 Desktop Runtime。将回退到 Web 渲染器。"],
  "Host.ExeMissing": ["The WPF preview host executable is missing from the extension. Falling back to the web renderer.", "Brak pliku wykonywalnego hosta podglądu WPF w rozszerzeniu. Przełączam na renderer web.", "Falta el ejecutable del host de vista previa WPF en la extensión. Se usará el renderizador web.", "Die ausführbare Datei des WPF-Vorschau-Hosts fehlt in der Erweiterung. Es wird auf den Web-Renderer zurückgegriffen.", "L'exécutable de l'hôte d'aperçu WPF est absent de l'extension. Retour au moteur de rendu web.", "拡張機能に WPF プレビューホストの実行ファイルがありません。Web レンダラーに切り替えます。", "扩展中缺少 WPF 预览主机可执行文件。将回退到 Web 渲染器。"],
  "Host.Crashed": ["The WPF preview host failed to start. Falling back to the web renderer.", "Host podglądu WPF nie wystartował. Przełączam na renderer web.", "El host de vista previa WPF no se pudo iniciar. Se usará el renderizador web.", "Der WPF-Vorschau-Host konnte nicht gestartet werden. Es wird auf den Web-Renderer zurückgegriffen.", "L'hôte d'aperçu WPF n'a pas pu démarrer. Retour au moteur de rendu web.", "WPF プレビューホストを起動できませんでした。Web レンダラーに切り替えます。", "WPF 预览主机启动失败。将回退到 Web 渲染器。"],
  "Host.Download": ["Download .NET 10 Desktop Runtime", "Pobierz .NET 10 Desktop Runtime", "Descargar .NET 10 Desktop Runtime", ".NET 10 Desktop Runtime herunterladen", "Télécharger .NET 10 Desktop Runtime", ".NET 10 Desktop Runtime をダウンロード", "下载 .NET 10 Desktop Runtime"],
  "Host.SwitchWeb": ["Use the web renderer", "Używaj renderera web", "Usar el renderizador web", "Web-Renderer verwenden", "Utiliser le moteur de rendu web", "Web レンダラーを使う", "使用 Web 渲染器"],
  "Host.ShowDetails": ["Show details", "Pokaż szczegóły", "Mostrar detalles", "Details anzeigen", "Afficher les détails", "詳細を表示", "显示详细信息"],
  "Engine.Web": ["Web", "Web", "Web", "Web", "Web", "Web", "Web"],
  "Engine.Wpf": ["WPF host", "Host WPF", "Host WPF", "WPF-Host", "Hôte WPF", "WPF ホスト", "WPF 主机"],
  "Resources.DialogTitle": ["Project resources", "Zasoby projektu", "Recursos del proyecto", "Projektressourcen", "Ressources du projet", "プロジェクトのリソース", "项目资源"],
  "Resources.Engine": ["Engine", "Silnik", "Motor", "Engine", "Moteur", "エンジン", "引擎"],
  "Resources.Language": ["Language", "Język", "Idioma", "Sprache", "Langue", "言語", "语言"],
  "Resources.ReflectCulture": ["Force in host", "Wymuś w hoście", "Forzar en host", "Im Host erzwingen", "Forcer dans l'hôte", "ホストで強制", "在主机中强制"],
  "Resources.ReflectCultureTip": [
    "WPF host: force the language via reflection (sets a localization singleton's CurrentCulture in the project DLL, e.g. TranslationSource.Instance). Use when the app keys off the OS UI language.",
    "Host WPF: wymuś język przez refleksję (ustawia CurrentCulture singletonu lokalizacji w DLL projektu, np. TranslationSource.Instance). Użyj, gdy aplikacja trzyma się języka systemu.",
    "Host WPF: forzar el idioma por reflexión (establece CurrentCulture de un singleton de localización en la DLL, p. ej. TranslationSource.Instance).",
    "WPF-Host: Sprache per Reflexion erzwingen (setzt CurrentCulture eines Lokalisierungs-Singletons in der Projekt-DLL, z. B. TranslationSource.Instance).",
    "Hôte WPF : forcer la langue par réflexion (définit CurrentCulture d'un singleton de localisation dans la DLL, p. ex. TranslationSource.Instance).",
    "WPF ホスト: リフレクションで言語を強制（プロジェクト DLL のローカライズ シングルトンの CurrentCulture を設定、例: TranslationSource.Instance）。",
    "WPF 主机：通过反射强制语言（设置项目 DLL 中本地化单例的 CurrentCulture，例如 TranslationSource.Instance）。",
  ],
  "Resources.LoadBtn": ["Load project resources", "Załaduj zasoby projektu", "Cargar recursos del proyecto", "Projektressourcen laden", "Charger les ressources du projet", "プロジェクトのリソースを読み込む", "加载项目资源"],
  "Resources.UnloadBtn": ["Unload resources", "Odładuj zasoby", "Descargar recursos", "Ressourcen entladen", "Décharger les ressources", "リソースをアンロード", "卸载资源"],
  "Resources.PickResources": ["Select resources…", "Wybierz zasoby…", "Seleccionar recursos…", "Ressourcen auswählen…", "Sélectionner les ressources…", "リソースを選択…", "选择资源…"],
  "Resources.SharedByOther": ["Resources loaded by “{0}” (shared host)", "Zasoby załadowane przez „{0}” (host współdzielony)", "Recursos cargados por «{0}» (host compartido)", "Ressourcen geladen von „{0}“ (gemeinsamer Host)", "Ressources chargées par « {0} » (hôte partagé)", "「{0}」が読み込んだリソース（共有ホスト）", "由“{0}”加载的资源（共享主机）"],
  "Host.LogEmpty": ["No entries yet.", "Brak wpisów.", "Sin entradas.", "Keine Einträge.", "Aucune entrée.", "エントリはまだありません。", "暂无条目。"],
  "Host.ShowErrors": ["Show errors in code", "Pokaż błędy w kodzie", "Mostrar errores en el código", "Fehler im Code anzeigen", "Afficher les erreurs dans le code", "コードにエラーを表示", "在代码中显示错误"],
  "Host.GoToError": ["Go to the error in the text editor", "Przejdź do błędu w edytorze tekstu", "Ir al error en el editor de texto", "Zum Fehler im Texteditor springen", "Aller à l'erreur dans l'éditeur de texte", "テキストエディターでエラーへ移動", "转到文本编辑器中的错误"],
  "Host.TabConsole": ["Console", "Konsola", "Consola", "Konsole", "Console", "コンソール", "控制台"],
  "Host.TabLog": ["Log", "Log", "Registro", "Protokoll", "Journal", "ログ", "日志"],
  "Host.Resources": ["Project resources", "Zasoby projektu", "Recursos del proyecto", "Projektressourcen", "Ressources du projet", "プロジェクトのリソース", "项目资源"],
  "Host.NoErrors": ["No active errors — the preview renders fine.", "Brak aktywnych błędów — podgląd renderuje się poprawnie.", "Sin errores activos: la vista previa se renderiza bien.", "Keine aktiven Fehler — die Vorschau wird korrekt gerendert.", "Aucune erreur active — l'aperçu s'affiche correctement.", "アクティブなエラーはありません — プレビューは正常です。", "无活动错误 — 预览渲染正常。"],
  "Host.NoResources": ["No project resources loaded.", "Nie załadowano zasobów projektu.", "No se cargaron recursos del proyecto.", "Keine Projektressourcen geladen.", "Aucune ressource de projet chargée.", "プロジェクトのリソースは読み込まれていません。", "未加载项目资源。"],
  "Host.AutoFix": ["Auto fix to", "Napraw na", "Corregir a", "Reparieren zu", "Corriger en", "自動修正:", "自动修正为"],
  "Tool.Select": ["Select", "Zaznacz", "Seleccionar", "Auswählen", "Sélection", "選択", "选择"],
  "Tool.SelectTip": ["Select / move / resize elements", "Zaznaczaj / przesuwaj / skaluj elementy", "Seleccionar / mover / redimensionar", "Auswählen / verschieben / skalieren", "Sélectionner / déplacer / redimensionner", "選択／移動／サイズ変更", "选择/移动/缩放元素"],
  "Tool.Pan": ["Pan", "Przesuń widok", "Desplazar", "Verschieben", "Déplacer la vue", "パン", "平移"],
  "Tool.PanTip": ["Drag to scroll the preview", "Przeciągnij, aby przewinąć podgląd", "Arrastra para desplazar la vista previa", "Ziehen, um die Vorschau zu scrollen", "Faites glisser pour faire défiler l'aperçu", "ドラッグでプレビューをスクロール", "拖动以滚动预览"],
  "Tool.Reorder": ["Reorder", "Zmień kolejność", "Reordenar", "Umordnen", "Réorganiser", "並べ替え", "重新排序"],
  "Tool.ReorderTip": ["Drag elements in the preview to reorder them", "Przeciągaj elementy w podglądzie, aby zmienić ich kolejność", "Arrastra elementos en la vista previa para reordenarlos", "Elemente in der Vorschau ziehen, um sie umzuordnen", "Faites glisser les éléments dans l'aperçu pour les réorganiser", "プレビューで要素をドラッグして並べ替え", "在预览中拖动元素以重新排序"],
  "Preview.AutoReveal": ["Auto-preview menus and lists", "Auto-podgląd menu i list", "Vista previa automática de menús y listas", "Menüs und Listen automatisch anzeigen", "Aperçu automatique des menus et listes", "メニューとリストの自動プレビュー", "自动预览菜单和列表"],
  "Preview.AutoRevealTip": ["Auto-open the dropdown/menu of the selected element", "Automatycznie rozwijaj listę/menu wybranego elementu", "Abrir automáticamente el menú del elemento seleccionado", "Dropdown/Menü des gewählten Elements automatisch öffnen", "Ouvrir automatiquement le menu de l'élément sélectionné", "選択要素のドロップダウン/メニューを自動的に開く", "自动展开所选元素的下拉/菜单"],
  "Tool.Grid": ["Grid", "Siatka", "Cuadrícula", "Raster", "Grille", "グリッド", "网格"],
  "Tool.GridStep": ["Step & snap", "Krok i przyciąganie", "Paso y ajuste", "Schritt & Einrasten", "Pas et magnétisme", "間隔とスナップ", "步长和对齐"],
  "Tool.ShowGrid": ["Show grid", "Pokaż siatkę", "Mostrar cuadrícula", "Raster anzeigen", "Afficher la grille", "グリッドを表示", "显示网格"],
  "Tool.Rulers": ["Rulers", "Linijki", "Reglas", "Lineale", "Règles", "ルーラー", "标尺"],
  "Tool.Guides": ["Guides", "Prowadnice", "Guías", "Hilfslinien", "Repères", "ガイド", "参考线"],
  "Guides.Title": ["Guides", "Prowadnice", "Guías", "Hilfslinien", "Repères", "ガイド", "参考线"],
  "Guides.PanelTitle": ["Guides & grid", "Prowadnice i siatka", "Guías y cuadrícula", "Hilfslinien & Raster", "Repères et grille", "ガイドとグリッド", "参考线和网格"],
  "Guides.NeedRulers": ["Enable rulers (in the toolbar) to see and drag guides.", "Włącz linijki (na pasku narzędzi), by widzieć i przeciągać prowadnice.", "Activa las reglas (en la barra) para ver y arrastrar guías.", "Lineale aktivieren (in der Symbolleiste), um Hilfslinien zu sehen und zu ziehen.", "Activez les règles (barre d'outils) pour voir et déplacer les repères.", "ルーラー（ツールバー）を有効にするとガイドを表示・ドラッグできます。", "在工具栏中启用标尺即可查看和拖动参考线。"],
  "Guides.Vertical": ["Vertical (from horizontal ruler)", "Pionowe (z linijki poziomej)", "Verticales (de la regla horizontal)", "Vertikal (vom horizontalen Lineal)", "Verticaux (de la règle horizontale)", "縦（水平ルーラーから）", "垂直（来自水平标尺）"],
  "Guides.Horizontal": ["Horizontal (from vertical ruler)", "Poziome (z linijki pionowej)", "Horizontales (de la regla vertical)", "Horizontal (vom vertikalen Lineal)", "Horizontaux (de la règle verticale)", "横（垂直ルーラーから）", "水平（来自垂直标尺）"],
  "Guides.AddV": ["Add vertical", "Dodaj pionową", "Agregar vertical", "Vertikale hinzufügen", "Ajouter vertical", "縦を追加", "添加垂直"],
  "Guides.AddH": ["Add horizontal", "Dodaj poziomą", "Agregar horizontal", "Horizontale hinzufügen", "Ajouter horizontal", "横を追加", "添加水平"],
  "Tool.ClearGuides": ["Clear guides", "Wyczyść prowadnice", "Borrar guías", "Hilfslinien löschen", "Effacer les repères", "ガイドを消去", "清除参考线"],
  "Tool.ClearGuidesTip": ["Remove all guides (click a ruler to add one)", "Usuń wszystkie prowadnice (kliknij linijkę, by dodać)", "Quitar todas las guías (haz clic en una regla para añadir)", "Alle Hilfslinien entfernen (Lineal anklicken zum Hinzufügen)", "Supprimer tous les repères (cliquez sur une règle pour en ajouter)", "すべてのガイドを削除（ルーラーをクリックで追加）", "移除所有参考线（点击标尺添加）"],
  "Ctx.RevertElement": ["Restore element from save", "Przywróć element z zapisu", "Restaurar elemento desde lo guardado", "Element aus Speicherstand wiederherstellen", "Restaurer l'élément depuis l'enregistrement", "保存内容から要素を復元", "从已保存内容还原元素"],
  "Ctx.CopyElement": ["Copy element", "Kopiuj element", "Copiar elemento", "Element kopieren", "Copier l'élément", "要素をコピー", "复制元素"],
  "Ctx.CutElement": ["Cut element", "Wytnij element", "Cortar elemento", "Element ausschneiden", "Couper l'élément", "要素を切り取り", "剪切元素"],
  "Ctx.NothingToPaste": ["Nothing to paste", "Nic do wklejenia", "Nada que pegar", "Nichts zum Einfügen", "Rien à coller", "貼り付けるものがありません", "没有可粘贴的内容"],
  "Ctx.PasteUnder": ["Paste under", "Wklej pod", "Pegar debajo", "Darunter einfügen", "Coller en dessous", "下に貼り付け", "粘贴到下方"],
  "Ctx.PasteInto": ["Paste into {0}", "Wklej w {0}", "Pegar en {0}", "Einfügen in {0}", "Coller dans {0}", "{0} に貼り付け", "粘贴到 {0}"],
  "Ctx.DeleteElement": ["Delete element", "Usuń element", "Eliminar elemento", "Element löschen", "Supprimer l'élément", "要素を削除", "删除元素"],
  "Ctx.SelectHeader": ["Select:", "Wybierz:", "Seleccionar:", "Auswählen:", "Sélectionner :", "選択:", "选择："],
  "Props.RevertAttr": ["Restore '{0}' from file", "Przywróć '{0}' z pliku", "Restaurar '{0}' del archivo", "'{0}' aus Datei wiederherstellen", "Restaurer '{0}' depuis le fichier", "'{0}' をファイルから復元", "从文件还原 '{0}'"],
  "Props.RevertAllAttrs": ["Restore all attributes of this element from file", "Przywróć wszystkie atrybuty tego elementu z pliku", "Restaurar todos los atributos de este elemento del archivo", "Alle Attribute dieses Elements aus Datei wiederherstellen", "Restaurer tous les attributs de cet élément depuis le fichier", "この要素のすべての属性をファイルから復元", "从文件还原此元素的所有属性"],
  "Zoom.In": ["Zoom in", "Powiększ", "Acercar", "Vergrößern", "Zoom avant", "拡大", "放大"],
  "Zoom.Out": ["Zoom out", "Pomniejsz", "Alejar", "Verkleinern", "Zoom arrière", "縮小", "缩小"],
  "Zoom.Reset": ["Reset zoom to 100%", "Przywróć zoom 100%", "Restablecer zoom al 100%", "Zoom auf 100% zurücksetzen", "Réinitialiser le zoom à 100%", "ズームを100%に戻す", "重置缩放为 100%"],
  "Zoom.Fit": ["Fit", "Dopasuj", "Ajustar", "Anpassen", "Ajuster", "全体", "适应"],
  "Zoom.FitTip": ["Fit the whole view to the window", "Dopasuj cały widok do okna", "Ajustar toda la vista a la ventana", "Gesamte Ansicht an das Fenster anpassen", "Ajuster toute la vue à la fenêtre", "ビュー全体をウィンドウに合わせる", "将整个视图适应窗口"],
  "Status.ParsedElements": ["{0} elements", "{0} elementów", "{0} elementos", "{0} Elemente", "{0} éléments", "{0} 個の要素", "{0} 个元素"],
  "Editor.OpenXamlFirst": ["XVE: open a .xaml file first.", "XVE: najpierw otwórz plik .xaml.", "XVE: primero abre un archivo .xaml.", "XVE: Öffnen Sie zuerst eine .xaml-Datei.", "XVE : ouvrez d'abord un fichier .xaml.", "XVE: 先に .xaml ファイルを開いてください。", "XVE：请先打开一个 .xaml 文件。"],
  "Run.WindowsOnly": ["Preview in a real Windows window is available only with the WPF engine on Windows.", "Podgląd w prawdziwym oknie Windows jest dostępny tylko przy użyciu silnika WPF na systemie Windows.", "La vista previa en una ventana real de Windows solo está disponible con el motor WPF en Windows.", "Die Vorschau in einem echten Windows-Fenster ist nur mit der WPF-Engine unter Windows verfügbar.", "L'aperçu dans une vraie fenêtre Windows n'est disponible qu'avec le moteur WPF sous Windows.", "実際の Windows ウィンドウでのプレビューは、Windows 上の WPF エンジンでのみ利用できます。", "在真实 Windows 窗口中的预览仅在 Windows 上使用 WPF 引擎时可用。"],
  "Resources.PickTitle": ["XVE: project resources “{0}”", "XVE: zasoby projektu „{0}”", "XVE: recursos del proyecto «{0}»", "XVE: Projektressourcen „{0}“", "XVE : ressources du projet « {0} »", "XVE: プロジェクトのリソース「{0}」", "XVE：项目资源“{0}”"],
  "Resources.PickPlaceholder": ["Select DLLs / styles / dictionaries to preview (Esc = skip)", "Wybierz DLL / style / słowniki do podglądu (Esc = pomiń)", "Selecciona DLL / estilos / diccionarios para la vista previa (Esc = omitir)", "DLLs / Stile / Wörterbücher für die Vorschau auswählen (Esc = überspringen)", "Sélectionnez les DLL / styles / dictionnaires à prévisualiser (Échap = ignorer)", "プレビューする DLL / スタイル / 辞書を選択（Esc = スキップ）", "选择要预览的 DLL / 样式 / 字典（Esc = 跳过）"],
  "Resources.Loaded": ["Project resources “{0}”:", "Zasoby projektu „{0}”:", "Recursos del proyecto «{0}»:", "Projektressourcen „{0}“:", "Ressources du projet « {0} » :", "プロジェクトのリソース「{0}」:", "项目资源“{0}”："],
  "Resources.Skip": ["Project resources skipped (built-in types preview).", "Zasoby projektu pominięte (podgląd typów wbudowanych).", "Recursos del proyecto omitidos (vista previa de tipos integrados).", "Projektressourcen übersprungen (Vorschau integrierter Typen).", "Ressources du projet ignorées (aperçu des types intégrés).", "プロジェクトのリソースをスキップ（組み込み型のプレビュー）。", "已跳过项目资源（内置类型预览）。"],
  "Resources.LoadFailed": ["Loading resources failed: {0}", "Ładowanie zasobów nie powiodło się: {0}", "Error al cargar los recursos: {0}", "Laden der Ressourcen fehlgeschlagen: {0}", "Échec du chargement des ressources : {0}", "リソースの読み込みに失敗しました: {0}", "加载资源失败：{0}"],
  "Common.Error": ["error", "błąd", "error", "Fehler", "erreur", "エラー", "错误"],
  "Host.RenderError": ["Render: {0}", "Render: {0}", "Renderizado: {0}", "Rendern: {0}", "Rendu : {0}", "レンダリング: {0}", "渲染：{0}"],
  "Resources.Libraries": ["Libraries: {0}", "Biblioteki: {0}", "Bibliotecas: {0}", "Bibliotheken: {0}", "Bibliothèques : {0}", "ライブラリ: {0}", "库：{0}"],
  "Resources.Dictionaries": ["Dictionaries: {0}", "Słowniki: {0}", "Diccionarios: {0}", "Wörterbücher: {0}", "Dictionnaires : {0}", "辞書: {0}", "字典：{0}"],
  "Resources.Localization": ["Localization: {0}", "Lokalizacja: {0}", "Localización: {0}", "Lokalisierung: {0}", "Localisation : {0}", "ローカライズ: {0}", "本地化：{0}"],
  "Resources.Skipped": ["skipped", "pominięto", "omitido", "übersprungen", "ignoré", "スキップ", "已跳过"],
  "Resource.Kind.Dll": ["library", "biblioteka", "biblioteca", "Bibliothek", "bibliothèque", "ライブラリ", "库"],
  "Resource.Kind.AppResources": ["application styles", "style aplikacji", "estilos de la aplicación", "Anwendungsstile", "styles de l'application", "アプリのスタイル", "应用样式"],
  "Resource.Kind.ResourceDict": ["resource dictionary", "słownik zasobów", "diccionario de recursos", "Ressourcenwörterbuch", "dictionnaire de ressources", "リソース辞書", "资源字典"],
  "Status.PreviewSoon": [
    "Visual preview arrives in stage 1 — structure & source available now",
    "Podgląd wizualny w etapie 1 — na razie struktura i źródło",
    "La vista previa visual llega en la etapa 1 — estructura y código disponibles",
    "Visuelle Vorschau folgt in Stufe 1 — Struktur und Quelltext verfügbar",
    "L'aperçu visuel arrive à l'étape 1 — structure et source disponibles",
    "ビジュアルプレビューはステージ1で — 現在は構造とソース",
    "可视化预览将在第 1 阶段提供 — 当前可用结构与源代码",
  ],
};

let langIndex = 0;

/** Ustawia język po kodzie; pusty/nieznany = pierwszy z `fallbackChain` lub angielski. */
export function applyLanguage(code: string | undefined, fallbackChain: string[] = []): void {
  const candidates = [code, ...fallbackChain].filter(Boolean) as string[];
  for (const c of candidates) {
    const idx = LANGUAGES.findIndex((l) => l.code === c);
    if (idx >= 0) {
      langIndex = idx;
      return;
    }
  }
  langIndex = 0;
}

export function t(key: string): string {
  const v = MAP[key];
  if (!v) return key;
  const s = langIndex < v.length ? v[langIndex] : "";
  return s.length > 0 ? s : v[0];
}

export function f(key: string, ...args: unknown[]): string {
  return t(key).replace(/\{(\d+)\}/g, (_, i) => String(args[Number(i)] ?? ""));
}

/** Eksport całej mapy dla webview (żeby nie duplikować tłumaczeń po stronie iframe). */
export function dictionaryForIndex(index: number): Record<string, string> {
  const out: Record<string, string> = {};
  for (const [k, v] of Object.entries(MAP)) out[k] = index < v.length && v[index] ? v[index] : v[0];
  return out;
}

export function currentLanguageIndex(): number {
  return langIndex;
}
